version: "3.9"

services:
  redis:
    image: redis:6.2.6
    container_name: dev-redis
    volumes:
      - ./redis.conf:/redis.conf:rw
      - dev-redis-volume-data:/data:rw
    ports:
      - "6379:6379"
    command:
      - /bin/bash
      - -c
      - |
        touch ./users.acl
        redis-server /redis.conf

volumes:
  dev-redis-volume-data:
